# Nome: João Emanuel - Matricula: 162080263 - Data 18/agosto/2020

### Leitura de datasets utilizando a biblioteca Pandas (Dataframe)

In [4]:
import pandas as pd

In [5]:
!ls

Aula-01-Python-06-Agosto-2020.ipynb
Aula-01-Python-06-Agosto-2020.pdf
Aula-02-Listas-Dicionarios-Python-13-Agosto-2020.ipynb
Aula-02-Listas-Dicionarios-Python-13-Agosto-2020.pdf
Aula-02-Python-11-Agosto-2020.ipynb
Aula-02-Python-11-Agosto-2020.pdf
Aula-03-Dataframes-Python-13-Agosto-2020.ipynb
Aula-03-Dataframes-Python-13-Agosto-2020.pdf
Aula-03-Dataframes-Python-18-Agosto-2020.ipynb
caso_full.csv

In [6]:
url = 'caso_full.csv'
df = pd.read_csv(url)
len(df)

554845

In [7]:
df.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,São Paulo,3550308.0,2020-02-25,9,12252023.0,False,False,1,0.00816,2020-02-25,0.0,0,1,city,SP,1,0
1,NaN,35.0,2020-02-25,9,45919049.0,False,False,1,0.00218,2020-02-25,0.0,0,1,state,SP,1,0
2,São Paulo,3550308.0,2020-02-26,9,12252023.0,False,False,1,0.00816,2020-02-26,0.0,0,2,city,SP,0,0
3,NaN,35.0,2020-02-26,9,45919049.0,False,False,1,0.00218,2020-02-26,0.0,0,2,state,SP,0,0
4,São Paulo,3550308.0,2020-02-27,9,12252023.0,False,False,1,0.00816,2020-02-27,0.0,0,3,city,SP,0,0

In [8]:
# Estrutura do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 554845 entries, 0 to 554844
Data columns (total 17 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   city                                           550575 non-null  object
 1   city_ibge_code                                 552352 non-null  float64
 2   date                                           554845 non-null  object
 3   epidemiological_week                           554845 non-null  int64
 4   estimated_population_2019                      552352 non-null  float64
 5   is_last                                        554845 non-null  bool
 6   is_repeated                                    554845 non-null  bool
 7   last_available_confirmed                       554845 non-null  int64
 8   last_available_confirmed_per_100k_inhabitants  540486 non-null  float64
 9   last_available_date                            554845 non-null  object
 10  last_available_death_rate                      554845 non-null  float64
 11  last_available_deaths                          554845 non-null  int64
 12  order_for_place                                554845 non-null  int64
 13  place_type                                     554845 non-null  object
 14  state                                          554845 non-null  object
 15  new_confirmed                                  554845 non-null  int64
 16  new_deaths                                     554845 non-null  int64
dtypes: bool(2), float64(4), int64(6), object(5)
memory usage: 64.6+ MB

In [9]:
df.epidemiological_week.unique()

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34])

In [10]:
len(df)

554845

### Filtrando dados

In [11]:
df34 = df[ df.epidemiological_week == 34 ]
len(df34)

11137

In [12]:
df34.describe().T

,count,mean,std,min,25%,50%,75%,max
city_ibge_code,11099.0,3.235224e+06,1.009762e+06,11.00000,2.509503e+06,3.145208e+06,4.118352e+06,5.300108e+06
epidemiological_week,11137.0,3.400000e+01,0.000000e+00,34.00000,3.400000e+01,3.400000e+01,3.400000e+01,3.400000e+01
estimated_population_2019,11099.0,7.570160e+04,8.606384e+05,781.00000,5.529000e+03,1.181900e+04,2.602300e+04,4.591905e+07
last_available_confirmed,11137.0,1.201694e+03,1.295500e+04,0.00000,3.000000e+01,9.900000e+01,3.350000e+02,7.026650e+05
last_available_confirmed_per_100k_inhabitants,11072.0,1.208674e+03,1.204023e+03,6.51211,4.180082e+02,8.760315e+02,1.600985e+03,1.573006e+04
last_available_death_rate,11137.0,2.619329e-02,4.358609e-02,0.00000,0.000000e+00,1.680000e-02,3.330000e-02,1.000000e+00
last_available_deaths,11137.0,3.881611e+01,5.098721e+02,0.00000,0.000000e+00,2.000000e+00,7.000000e+00,2.689900e+04
order_for_place,11137.0,9.913989e+01,2.937640e+01,1.00000,8.100000e+01,1.010000e+02,1.210000e+02,1.750000e+02
new_confirmed,11137.0,7.162072e+00,9.108516e+01,-3048.00000,0.000000e+00,0.000000e+00,1.000000e+00,3.665000e+03
new_deaths,11137.0,2.130735e-01,2.688500e+00,-99.00000,0.000000e+00,0.000000e+00,0.000000e+00,9.100000e+01

In [13]:
pd.options.display.float_format = '{:.0f}'.format

In [14]:
df34.describe().T

,count,mean,std,min,25%,50%,75%,max
city_ibge_code,11099,3235224,1009762,11,2509503,3145208,4118352,5300108
epidemiological_week,11137,34,0,34,34,34,34,34
estimated_population_2019,11099,75702,860638,781,5529,11819,26023,45919049
last_available_confirmed,11137,1202,12955,0,30,99,335,702665
last_available_confirmed_per_100k_inhabitants,11072,1209,1204,7,418,876,1601,15730
last_available_death_rate,11137,0,0,0,0,0,0,1
last_available_deaths,11137,39,510,0,0,2,7,26899
order_for_place,11137,99,29,1,81,101,121,175
new_confirmed,11137,7,91,-3048,0,0,1,3665
new_deaths,11137,0,3,-99,0,0,0,91

In [15]:
len(df34.city.unique())

5256

In [16]:
df34.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
543708,Acrelândia,1200013,2020-08-16,34,15256,True,False,373,2445,2020-08-16,0,8,141,city,AC,0,0
543709,Assis Brasil,1200054,2020-08-16,34,7417,True,False,438,5905,2020-08-16,0,9,108,city,AC,-1,0
543710,Brasiléia,1200104,2020-08-16,34,26278,True,False,936,3562,2020-08-16,0,14,100,city,AC,0,0
543711,Bujari,1200138,2020-08-16,34,10266,True,False,352,3429,2020-08-16,0,6,131,city,AC,1,0
543712,Capixaba,1200179,2020-08-16,34,11733,True,False,239,2037,2020-08-16,0,7,101,city,AC,0,0

In [17]:
df34.date.unique()

array(['2020-08-16', '2020-08-17'], dtype=object)

In [18]:
# Semana Epidemiológica 34
len(df34)

11137

In [19]:
# Data = '2020-08-17'
df16 = df34[ df34.date == '2020-08-17'].reset_index(drop=True)
len(df16)

5569

In [20]:
df16.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,Acrelândia,1200013,2020-08-17,34,15256,False,True,373,2445,2020-08-16,0,8,142,city,AC,0,0
1,Assis Brasil,1200054,2020-08-17,34,7417,False,True,438,5905,2020-08-16,0,9,109,city,AC,0,0
2,Brasiléia,1200104,2020-08-17,34,26278,False,True,936,3562,2020-08-16,0,14,101,city,AC,0,0
3,Bujari,1200138,2020-08-17,34,10266,False,True,352,3429,2020-08-16,0,6,132,city,AC,0,0
4,Capixaba,1200179,2020-08-17,34,11733,False,True,239,2037,2020-08-16,0,7,102,city,AC,0,0

In [21]:
df16.city.value_counts()

Importados/Indefinidos    19
Bom Jesus                  5
Vera Cruz                  4
Planalto                   4
Bonito                     4
                          ..
Capistrano                 1
Rio das Flores             1
Frutal                     1
Baía da Traição            1
Chaval                     1
Name: city, Length: 5255, dtype: int64

In [22]:
df16.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,Acrelândia,1200013,2020-08-17,34,15256,False,True,373,2445,2020-08-16,0,8,142,city,AC,0,0
1,Assis Brasil,1200054,2020-08-17,34,7417,False,True,438,5905,2020-08-16,0,9,109,city,AC,0,0
2,Brasiléia,1200104,2020-08-17,34,26278,False,True,936,3562,2020-08-16,0,14,101,city,AC,0,0
3,Bujari,1200138,2020-08-17,34,10266,False,True,352,3429,2020-08-16,0,6,132,city,AC,0,0
4,Capixaba,1200179,2020-08-17,34,11733,False,True,239,2037,2020-08-16,0,7,102,city,AC,0,0

In [23]:
df_novos_casos = df16[ df16.new_confirmed > 0 ].reset_index(drop=True)
len(df_novos_casos)

1880

In [24]:
df_novos_casos.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,Arapiraca,2700300,2020-08-17,34,231747,True,False,9895,4270,2020-08-17,0,123,122,city,AL,13,1
1,Atalaia,2700409,2020-08-17,34,47185,True,False,540,1144,2020-08-17,0,17,114,city,AL,1,0
2,Barra de São Miguel,2700607,2020-08-17,34,8322,True,False,129,1550,2020-08-17,0,5,111,city,AL,1,0
3,Cajueiro,2701308,2020-08-17,34,21264,True,False,228,1072,2020-08-17,0,12,100,city,AL,1,0
4,Campestre,2701357,2020-08-17,34,6936,True,False,89,1283,2020-08-17,0,3,103,city,AL,1,0